#!/usr/bin/env node
/**
 * Auto-generate `src/types/country-codes.ts` from the contents of
 * `src/assets/maps/`. Produces a literal-union `CountryCode` type and a
 * `COUNTRY_CODES` runtime array. Keeps consumer-facing autocomplete in
 * lockstep with the actual SVG assets shipped.
 */
import { readdirSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const SRC_DIR = join(ROOT, 'src/assets/maps')
const OUT = join(ROOT, 'src/types/country-codes.ts')

if (!existsSync(SRC_DIR)) {
  console.error(`Source directory missing: ${SRC_DIR}`)
  process.exit(1)
}

const codes = readdirSync(SRC_DIR)
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.replace(/\.svg$/, '').toLowerCase())
  .sort()

if (codes.length === 0) {
  console.error('No SVG files found in', SRC_DIR)
  process.exit(1)
}

// Group ten per line for readability without producing an unwieldy union.
const chunk = (arr, n) =>
  Array.from({ length: Math.ceil(arr.length / n) }, (_, i) =>
    arr.slice(i * n, i * n + n)
  )

const unionLines = chunk(codes, 10)
  .map((row, i) => {
    const prefix = i === 0 ? '  =' : '  |'
    return `${prefix} ${row.map((c) => `'${c}'`).join(' | ')}`
  })

const out = [
  '// AUTO-GENERATED by scripts/generate-types.mjs — do not edit by hand.',
  '// Regenerated on every `npm run build` from `src/assets/maps/`.',
  '',
  'export type CountryCode',
  ...unionLines,
  '',
].join('\n')

writeFileSync(OUT, out)
console.log(`[generate-types] wrote ${codes.length} codes to ${OUT}`)
