import type { Country } from './types'

/**
 * Master list of countries and territories shipped with this package.
 * Each entry has a corresponding SVG in `src/assets/maps/{code}.svg`.
 *
 * Codes follow ISO 3166-1 alpha-2 (lowercase). Names are the common
 * English short forms; `officialName` is the longer formal style for
 * consumers who need it. The array is laid out by code for editing
 * convenience; the public `countries` export is sorted A–Z by name.
 */
const COUNTRY_LIST: readonly Country[] = [
  { code: 'ad', name: 'Andorra', officialName: 'Principality of Andorra' },
  { code: 'ae', name: 'United Arab Emirates', officialName: 'United Arab Emirates' },
  { code: 'af', name: 'Afghanistan', officialName: 'Islamic Republic of Afghanistan' },
  { code: 'ag', name: 'Antigua and Barbuda', officialName: 'Antigua and Barbuda' },
  { code: 'al', name: 'Albania', officialName: 'Republic of Albania' },
  { code: 'am', name: 'Armenia', officialName: 'Republic of Armenia' },
  { code: 'ao', name: 'Angola', officialName: 'Republic of Angola' },
  { code: 'ar', name: 'Argentina', officialName: 'Argentine Republic' },
  { code: 'at', name: 'Austria', officialName: 'Republic of Austria' },
  { code: 'au', name: 'Australia', officialName: 'Commonwealth of Australia' },
  { code: 'az', name: 'Azerbaijan', officialName: 'Republic of Azerbaijan' },
  { code: 'ba', name: 'Bosnia and Herzegovina', officialName: 'Bosnia and Herzegovina' },
  { code: 'bb', name: 'Barbados', officialName: 'Barbados' },
  { code: 'bd', name: 'Bangladesh', officialName: "People's Republic of Bangladesh" },
  { code: 'be', name: 'Belgium', officialName: 'Kingdom of Belgium' },
  { code: 'bf', name: 'Burkina Faso', officialName: 'Burkina Faso' },
  { code: 'bg', name: 'Bulgaria', officialName: 'Republic of Bulgaria' },
  { code: 'bh', name: 'Bahrain', officialName: 'Kingdom of Bahrain' },
  { code: 'bi', name: 'Burundi', officialName: 'Republic of Burundi' },
  { code: 'bj', name: 'Benin', officialName: 'Republic of Benin' },
  { code: 'bn', name: 'Brunei', officialName: 'Nation of Brunei, the Abode of Peace' },
  { code: 'bo', name: 'Bolivia', officialName: 'Plurinational State of Bolivia' },
  { code: 'br', name: 'Brazil', officialName: 'Federative Republic of Brazil' },
  { code: 'bs', name: 'Bahamas', officialName: 'Commonwealth of The Bahamas' },
  { code: 'bt', name: 'Bhutan', officialName: 'Kingdom of Bhutan' },
  { code: 'bw', name: 'Botswana', officialName: 'Republic of Botswana' },
  { code: 'by', name: 'Belarus', officialName: 'Republic of Belarus' },
  { code: 'bz', name: 'Belize', officialName: 'Belize' },
  { code: 'ca', name: 'Canada', officialName: 'Canada' },
  { code: 'cd', name: 'Democratic Republic of the Congo', officialName: 'Democratic Republic of the Congo' },
  { code: 'cf', name: 'Central African Republic', officialName: 'Central African Republic' },
  { code: 'cg', name: 'Republic of the Congo', officialName: 'Republic of the Congo' },
  { code: 'ch', name: 'Switzerland', officialName: 'Swiss Confederation' },
  { code: 'ci', name: "Côte d'Ivoire", officialName: "Republic of Côte d'Ivoire" },
  { code: 'cl', name: 'Chile', officialName: 'Republic of Chile' },
  { code: 'cm', name: 'Cameroon', officialName: 'Republic of Cameroon' },
  { code: 'cn', name: 'China', officialName: "People's Republic of China" },
  { code: 'co', name: 'Colombia', officialName: 'Republic of Colombia' },
  { code: 'cr', name: 'Costa Rica', officialName: 'Republic of Costa Rica' },
  { code: 'cu', name: 'Cuba', officialName: 'Republic of Cuba' },
  { code: 'cv', name: 'Cape Verde', officialName: 'Republic of Cabo Verde' },
  { code: 'cy', name: 'Cyprus', officialName: 'Republic of Cyprus' },
  { code: 'cz', name: 'Czechia', officialName: 'Czech Republic' },
  { code: 'de', name: 'Germany', officialName: 'Federal Republic of Germany' },
  { code: 'dj', name: 'Djibouti', officialName: 'Republic of Djibouti' },
  { code: 'dk', name: 'Denmark', officialName: 'Kingdom of Denmark' },
  { code: 'dm', name: 'Dominica', officialName: 'Commonwealth of Dominica' },
  { code: 'do', name: 'Dominican Republic', officialName: 'Dominican Republic' },
  { code: 'dz', name: 'Algeria', officialName: "People's Democratic Republic of Algeria" },
  { code: 'ec', name: 'Ecuador', officialName: 'Republic of Ecuador' },
  { code: 'ee', name: 'Estonia', officialName: 'Republic of Estonia' },
  { code: 'eg', name: 'Egypt', officialName: 'Arab Republic of Egypt' },
  { code: 'er', name: 'Eritrea', officialName: 'State of Eritrea' },
  { code: 'es', name: 'Spain', officialName: 'Kingdom of Spain' },
  { code: 'et', name: 'Ethiopia', officialName: 'Federal Democratic Republic of Ethiopia' },
  { code: 'fi', name: 'Finland', officialName: 'Republic of Finland' },
  { code: 'fj', name: 'Fiji', officialName: 'Republic of Fiji' },
  { code: 'fm', name: 'Micronesia', officialName: 'Federated States of Micronesia' },
  { code: 'fr', name: 'France', officialName: 'French Republic' },
  { code: 'ga', name: 'Gabon', officialName: 'Gabonese Republic' },
  { code: 'gb', name: 'United Kingdom', officialName: 'United Kingdom of Great Britain and Northern Ireland' },
  { code: 'gd', name: 'Grenada', officialName: 'Grenada' },
  { code: 'ge', name: 'Georgia', officialName: 'Georgia' },
  { code: 'gh', name: 'Ghana', officialName: 'Republic of Ghana' },
  { code: 'gm', name: 'Gambia', officialName: 'Republic of The Gambia' },
  { code: 'gn', name: 'Guinea', officialName: 'Republic of Guinea' },
  { code: 'gq', name: 'Equatorial Guinea', officialName: 'Republic of Equatorial Guinea' },
  { code: 'gr', name: 'Greece', officialName: 'Hellenic Republic' },
  { code: 'gt', name: 'Guatemala', officialName: 'Republic of Guatemala' },
  { code: 'gw', name: 'Guinea-Bissau', officialName: 'Republic of Guinea-Bissau' },
  { code: 'gy', name: 'Guyana', officialName: 'Co-operative Republic of Guyana' },
  { code: 'hn', name: 'Honduras', officialName: 'Republic of Honduras' },
  { code: 'hr', name: 'Croatia', officialName: 'Republic of Croatia' },
  { code: 'ht', name: 'Haiti', officialName: 'Republic of Haiti' },
  { code: 'hu', name: 'Hungary', officialName: 'Hungary' },
  { code: 'id', name: 'Indonesia', officialName: 'Republic of Indonesia' },
  { code: 'ie', name: 'Ireland', officialName: 'Ireland' },
  { code: 'il', name: 'Israel', officialName: 'State of Israel' },
  { code: 'in', name: 'India', officialName: 'Republic of India' },
  { code: 'iq', name: 'Iraq', officialName: 'Republic of Iraq' },
  { code: 'ir', name: 'Iran', officialName: 'Islamic Republic of Iran' },
  { code: 'is', name: 'Iceland', officialName: 'Iceland' },
  { code: 'it', name: 'Italy', officialName: 'Italian Republic' },
  { code: 'jm', name: 'Jamaica', officialName: 'Jamaica' },
  { code: 'jo', name: 'Jordan', officialName: 'Hashemite Kingdom of Jordan' },
  { code: 'jp', name: 'Japan', officialName: 'Japan' },
  { code: 'ke', name: 'Kenya', officialName: 'Republic of Kenya' },
  { code: 'kg', name: 'Kyrgyzstan', officialName: 'Kyrgyz Republic' },
  { code: 'kh', name: 'Cambodia', officialName: 'Kingdom of Cambodia' },
  { code: 'ki', name: 'Kiribati', officialName: 'Republic of Kiribati' },
  { code: 'km', name: 'Comoros', officialName: 'Union of the Comoros' },
  { code: 'kn', name: 'Saint Kitts and Nevis', officialName: 'Federation of Saint Christopher and Nevis' },
  { code: 'kp', name: 'North Korea', officialName: "Democratic People's Republic of Korea" },
  { code: 'kr', name: 'South Korea', officialName: 'Republic of Korea' },
  { code: 'kw', name: 'Kuwait', officialName: 'State of Kuwait' },
  { code: 'kz', name: 'Kazakhstan', officialName: 'Republic of Kazakhstan' },
  { code: 'la', name: 'Laos', officialName: "Lao People's Democratic Republic" },
  { code: 'lb', name: 'Lebanon', officialName: 'Lebanese Republic' },
  { code: 'lc', name: 'Saint Lucia', officialName: 'Saint Lucia' },
  { code: 'li', name: 'Liechtenstein', officialName: 'Principality of Liechtenstein' },
  { code: 'lk', name: 'Sri Lanka', officialName: 'Democratic Socialist Republic of Sri Lanka' },
  { code: 'lr', name: 'Liberia', officialName: 'Republic of Liberia' },
  { code: 'ls', name: 'Lesotho', officialName: 'Kingdom of Lesotho' },
  { code: 'lt', name: 'Lithuania', officialName: 'Republic of Lithuania' },
  { code: 'lu', name: 'Luxembourg', officialName: 'Grand Duchy of Luxembourg' },
  { code: 'lv', name: 'Latvia', officialName: 'Republic of Latvia' },
  { code: 'ly', name: 'Libya', officialName: 'State of Libya' },
  { code: 'ma', name: 'Morocco', officialName: 'Kingdom of Morocco' },
  { code: 'mc', name: 'Monaco', officialName: 'Principality of Monaco' },
  { code: 'md', name: 'Moldova', officialName: 'Republic of Moldova' },
  { code: 'me', name: 'Montenegro', officialName: 'Montenegro' },
  { code: 'mg', name: 'Madagascar', officialName: 'Republic of Madagascar' },
  { code: 'mh', name: 'Marshall Islands', officialName: 'Republic of the Marshall Islands' },
  { code: 'mk', name: 'North Macedonia', officialName: 'Republic of North Macedonia' },
  { code: 'ml', name: 'Mali', officialName: 'Republic of Mali' },
  { code: 'mm', name: 'Myanmar', officialName: 'Republic of the Union of Myanmar' },
  { code: 'mn', name: 'Mongolia', officialName: 'Mongolia' },
  { code: 'mr', name: 'Mauritania', officialName: 'Islamic Republic of Mauritania' },
  { code: 'mt', name: 'Malta', officialName: 'Republic of Malta' },
  { code: 'mu', name: 'Mauritius', officialName: 'Republic of Mauritius' },
  { code: 'mv', name: 'Maldives', officialName: 'Republic of Maldives' },
  { code: 'mw', name: 'Malawi', officialName: 'Republic of Malawi' },
  { code: 'mx', name: 'Mexico', officialName: 'United Mexican States' },
  { code: 'my', name: 'Malaysia', officialName: 'Malaysia' },
  { code: 'mz', name: 'Mozambique', officialName: 'Republic of Mozambique' },
  { code: 'na', name: 'Namibia', officialName: 'Republic of Namibia' },
  { code: 'ne', name: 'Niger', officialName: 'Republic of the Niger' },
  { code: 'ng', name: 'Nigeria', officialName: 'Federal Republic of Nigeria' },
  { code: 'ni', name: 'Nicaragua', officialName: 'Republic of Nicaragua' },
  { code: 'nl', name: 'Netherlands', officialName: 'Kingdom of the Netherlands' },
  { code: 'no', name: 'Norway', officialName: 'Kingdom of Norway' },
  { code: 'np', name: 'Nepal', officialName: 'Federal Democratic Republic of Nepal' },
  { code: 'nr', name: 'Nauru', officialName: 'Republic of Nauru' },
  { code: 'nz', name: 'New Zealand', officialName: 'New Zealand' },
  { code: 'om', name: 'Oman', officialName: 'Sultanate of Oman' },
  { code: 'pa', name: 'Panama', officialName: 'Republic of Panama' },
  { code: 'pe', name: 'Peru', officialName: 'Republic of Peru' },
  { code: 'pg', name: 'Papua New Guinea', officialName: 'Independent State of Papua New Guinea' },
  { code: 'ph', name: 'Philippines', officialName: 'Republic of the Philippines' },
  { code: 'pk', name: 'Pakistan', officialName: 'Islamic Republic of Pakistan' },
  { code: 'pl', name: 'Poland', officialName: 'Republic of Poland' },
  { code: 'ps', name: 'Palestine', officialName: 'State of Palestine' },
  { code: 'pt', name: 'Portugal', officialName: 'Portuguese Republic' },
  { code: 'pw', name: 'Palau', officialName: 'Republic of Palau' },
  { code: 'py', name: 'Paraguay', officialName: 'Republic of Paraguay' },
  { code: 'qa', name: 'Qatar', officialName: 'State of Qatar' },
  { code: 'ro', name: 'Romania', officialName: 'Romania' },
  { code: 'rs', name: 'Serbia', officialName: 'Republic of Serbia' },
  { code: 'ru', name: 'Russia', officialName: 'Russian Federation' },
  { code: 'rw', name: 'Rwanda', officialName: 'Republic of Rwanda' },
  { code: 'sa', name: 'Saudi Arabia', officialName: 'Kingdom of Saudi Arabia' },
  { code: 'sb', name: 'Solomon Islands', officialName: 'Solomon Islands' },
  { code: 'sc', name: 'Seychelles', officialName: 'Republic of Seychelles' },
  { code: 'sd', name: 'Sudan', officialName: 'Republic of the Sudan' },
  { code: 'se', name: 'Sweden', officialName: 'Kingdom of Sweden' },
  { code: 'sg', name: 'Singapore', officialName: 'Republic of Singapore' },
  { code: 'si', name: 'Slovenia', officialName: 'Republic of Slovenia' },
  { code: 'sk', name: 'Slovakia', officialName: 'Slovak Republic' },
  { code: 'sl', name: 'Sierra Leone', officialName: 'Republic of Sierra Leone' },
  { code: 'sm', name: 'San Marino', officialName: 'Republic of San Marino' },
  { code: 'sn', name: 'Senegal', officialName: 'Republic of Senegal' },
  { code: 'so', name: 'Somalia', officialName: 'Federal Republic of Somalia' },
  { code: 'sr', name: 'Suriname', officialName: 'Republic of Suriname' },
  { code: 'ss', name: 'South Sudan', officialName: 'Republic of South Sudan' },
  { code: 'st', name: 'São Tomé and Príncipe', officialName: 'Democratic Republic of São Tomé and Príncipe' },
  { code: 'sv', name: 'El Salvador', officialName: 'Republic of El Salvador' },
  { code: 'sy', name: 'Syria', officialName: 'Syrian Arab Republic' },
  { code: 'sz', name: 'Eswatini', officialName: 'Kingdom of Eswatini' },
  { code: 'td', name: 'Chad', officialName: 'Republic of Chad' },
  { code: 'tg', name: 'Togo', officialName: 'Togolese Republic' },
  { code: 'th', name: 'Thailand', officialName: 'Kingdom of Thailand' },
  { code: 'tj', name: 'Tajikistan', officialName: 'Republic of Tajikistan' },
  { code: 'tl', name: 'Timor-Leste', officialName: 'Democratic Republic of Timor-Leste' },
  { code: 'tm', name: 'Turkmenistan', officialName: 'Turkmenistan' },
  { code: 'tn', name: 'Tunisia', officialName: 'Republic of Tunisia' },
  { code: 'to', name: 'Tonga', officialName: 'Kingdom of Tonga' },
  { code: 'tr', name: 'Turkey', officialName: 'Republic of Türkiye' },
  { code: 'tt', name: 'Trinidad and Tobago', officialName: 'Republic of Trinidad and Tobago' },
  { code: 'tv', name: 'Tuvalu', officialName: 'Tuvalu' },
  { code: 'tz', name: 'Tanzania', officialName: 'United Republic of Tanzania' },
  { code: 'ua', name: 'Ukraine', officialName: 'Ukraine' },
  { code: 'ug', name: 'Uganda', officialName: 'Republic of Uganda' },
  { code: 'us', name: 'United States', officialName: 'United States of America' },
  { code: 'uy', name: 'Uruguay', officialName: 'Oriental Republic of Uruguay' },
  { code: 'uz', name: 'Uzbekistan', officialName: 'Republic of Uzbekistan' },
  { code: 'va', name: 'Vatican City', officialName: 'Holy See (Vatican City State)' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', officialName: 'Saint Vincent and the Grenadines' },
  { code: 've', name: 'Venezuela', officialName: 'Bolivarian Republic of Venezuela' },
  { code: 'vn', name: 'Vietnam', officialName: 'Socialist Republic of Vietnam' },
  { code: 'vu', name: 'Vanuatu', officialName: 'Republic of Vanuatu' },
  { code: 'ws', name: 'Samoa', officialName: 'Independent State of Samoa' },
  { code: 'ye', name: 'Yemen', officialName: 'Republic of Yemen' },
  { code: 'za', name: 'South Africa', officialName: 'Republic of South Africa' },
  { code: 'zm', name: 'Zambia', officialName: 'Republic of Zambia' },
  { code: 'zw', name: 'Zimbabwe', officialName: 'Republic of Zimbabwe' },
]

export const countries: readonly Country[] = [...COUNTRY_LIST].sort((a, b) =>
  a.name.localeCompare(b.name, 'en')
)

const countriesByCode: Record<string, Country> = Object.fromEntries(
  countries.map((c) => [c.code, c])
)

export function getCountry(code: string): Country | undefined {
  return countriesByCode[code.toLowerCase()]
}

export const countryCodes: readonly string[] = countries.map((c) => c.code)
